name: Deploy to LightSail

on:
  push:
    branches:
      - dev  # Trigger the workflow on push to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH using the private key from GitHub secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to LightSail instance
      - name: Deploy to LightSail
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.170.217.92 "cd /var/www/html && git pull origin dev"
